services:
  exodus-subscription-page:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - SUB_GRPC_ADDRESS=${SUB_GRPC_ADDRESS:-0.0.0.0}
      - SUB_GRPC_PORT=${SUB_GRPC_PORT:-2222}
      - SUB_PATH=${SUB_PATH:-/}
      - SUB_GRPC_TOKEN=${SUB_GRPC_TOKEN:-}
      - SUB_SECRET_KEY=${SUB_SECRET_KEY:-}
    ports:
      - '127.0.0.1:3010:3010'
