CREATE TABLE IF NOT EXISTS public.node_plugins (
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    plugin_config jsonb NOT NULL DEFAULT '{"ingressFilter":{"enabled":false,"blockedIps":[]},"egressFilter":{"enabled":false,"blockedIps":[],"blockedPorts":[]},"haproxyAuth":{"enabled":false},"sharedLists":[]}'::jsonb,
    view_position integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(3) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(3) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT node_plugins_pkey PRIMARY KEY (uuid),
    CONSTRAINT node_plugins_name_key UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS node_plugins_view_position_idx ON public.node_plugins(view_position);

INSERT INTO public.node_plugins (name, plugin_config)
SELECT
    'HAProxy Auth',
    '{"ingressFilter":{"enabled":false,"blockedIps":[]},"egressFilter":{"enabled":false,"blockedIps":[],"blockedPorts":[]},"haproxyAuth":{"enabled":true},"sharedLists":[]}'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM public.node_plugins WHERE name = 'HAProxy Auth'
);
