# v2ray-stat-subscription Configuration File
# This file specifies paths and settings for the v2ray-stat monitoring application.

# Log Settings
log:
  loglevel: trace                                          # Logging level: none, error, warn, info, debug, trace. NONE disables logging; each level includes messages from lower levels.
  logmode: inclusive                                      # Log mode: inclusive = this and lower levels; exclusive = only this level

# Timezone Settings 
timezone: Asia/Bangkok                                    # IANA timezone name (e.g., Europe/Amsterdam, Asia/Singapore). If empty, uses TZ environment variable or UTC.

# V2RS-Sub Settings
v2rs-sub:
  address: 127.0.0.1                                      # Listening address for the subscription server. '127.0.0.1' restricts access to localhost.
  port: 9264                                              # Listening port for the subscription server. Must be between 1 and 65535.
  grpc_port: 9263                                         # Listening port for the gRPC server.

# Subscription Settings
subscription:
  domains:
    top: {domain}
    lol: {domain2}
  defaults:
    headers:
      Profile-Title: "base64:U3Vic2NyaXB0aW9u"
      Profile-Update-Interval: "12"
      Support-Url: "https://natribu.org/"
      Profile-Web-Page-Url: "https://natribu.org/"
      Announce: "ИДИ сюда (ง ͠° ͟ل͜ ͡°)ง"
    clients: ["xray"]
    nodes: ["lol", "top"]
    templates:
      base:
        rus: node_lol
      advanced:
        rus: node_lol
        de: node_top
  groups:
    premium:
      clients: ["xray", "singbox", "mihomo"]
      templates:
        base:
          rus: node_lol
          top: node_top
        advanced:
          rus: node_lol
          top: node_top
  users:
    premium:
      users: ["cortez", "user", "mama"]
