# v2ray-stat-subscription Configuration File
# This file specifies paths and settings for the v2ray-stat monitoring application.

# Log Settings
log_config:
  level: none                                           # Logging level: none, error, warn, info, debug, trace
  mode: inclusive                                       # Mode: inclusive (this and lower), exclusive (only this)

# Timezone Settings 
TZ: Asia/Bangkok                                        # IANA timezone name (e.g., Europe/Amsterdam, Asia/Singapore). If empty, uses TZ environment variable or UTC.

# V2RS-Sub Settings
subscription:
  listen_address: 127.0.0.1                                      # Listening address for the subscription server. '127.0.0.1' restricts access to localhost.
  listen_port: 9264                                              # Listening port for the subscription server. Must be between 1 and 65535.
  listen_grpc_port: 9263                                         # Listening port for the gRPC server.

node_metadata:
  rus:
    remark_plaсeholder: RUSSIAN
    domain_plaсeholder: example.com
    ip_plaсeholder: 1.2.3.6
    port_plaсeholder: 443
  top:
    remark_plaсeholder: NETHERLAND
    domain_plaсeholder: theleet.com
    ip_plaсeholder: 1.2.3.4
    port_plaсeholder: 8443

# Subscription Settings
sub_config:
  defaults:
    headers:
      Profile-Title: "base64:U3Vic2NyaXB0aW9u"
      Profile-Update-Interval: "12"
      Support-Url: "https://natribu.org/"
      Profile-Web-Page-Url: "https://natribu.org/"
      Announce: "ИДИ сюда (ง ͠° ͟ل͜ ͡°)ง"
    clients: ["xray"]
    nodes: ["lol", "top"]
    templates:
      base:
        rus: node_lol
      advanced:
        rus: node_lol
        top: node_top
  groups:
    premium:
      clients: ["xray", "singbox", "mihomo"]
      templates:
        base:
          rus: node_lol
          top: node_top
        advanced:
          rus: node_lol
          top: node_top
  users:
    premium:
      users: ["cortez", "user", "mama"]
