contact_links:
  - name: 🐞 Bug report
    url: https://github.com/cerberus/panel/issues/new/choose
    about: Please report any frontend/backend bugs on @cerberus/panel repository.
  - name: 💡 Feature request
    url: https://github.com/cerberus/panel/issues/new/choose
    about: Feel free to request any new features.
