// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdemo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Keygen struct {
	ID        pgtype.UUID        `json:"id"`
	PubKey    string             `json:"pub_key"`
	CaCert    string             `json:"ca_cert"`
	CaKey     string             `json:"ca_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NodePlugin struct {
	Uuid         pgtype.UUID        `json:"uuid"`
	Name         string             `json:"name"`
	PluginConfig []byte             `json:"plugin_config"`
	ViewPosition int32              `json:"view_position"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
