// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcdemo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodePlugin = `-- name: CreateNodePlugin :one
INSERT INTO node_plugins (uuid, name, plugin_config, view_position)
VALUES ($1, $2, $3, $4)
RETURNING uuid, name, plugin_config, view_position, created_at, updated_at
`

type CreateNodePluginParams struct {
	Uuid         pgtype.UUID `json:"uuid"`
	Name         string      `json:"name"`
	PluginConfig []byte      `json:"plugin_config"`
	ViewPosition int32       `json:"view_position"`
}

func (q *Queries) CreateNodePlugin(ctx context.Context, arg CreateNodePluginParams) (NodePlugin, error) {
	row := q.db.QueryRow(ctx, createNodePlugin,
		arg.Uuid,
		arg.Name,
		arg.PluginConfig,
		arg.ViewPosition,
	)
	var i NodePlugin
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PluginConfig,
		&i.ViewPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNodePlugin = `-- name: DeleteNodePlugin :exec
DELETE FROM node_plugins
WHERE uuid = $1
`

func (q *Queries) DeleteNodePlugin(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNodePlugin, uuid)
	return err
}

const getKeygenCredentials = `-- name: GetKeygenCredentials :one
SELECT pub_key, ca_cert, ca_key
FROM keygen
ORDER BY created_at ASC
LIMIT 1
`

type GetKeygenCredentialsRow struct {
	PubKey string `json:"pub_key"`
	CaCert string `json:"ca_cert"`
	CaKey  string `json:"ca_key"`
}

func (q *Queries) GetKeygenCredentials(ctx context.Context) (GetKeygenCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getKeygenCredentials)
	var i GetKeygenCredentialsRow
	err := row.Scan(&i.PubKey, &i.CaCert, &i.CaKey)
	return i, err
}

const getNodePluginByUUID = `-- name: GetNodePluginByUUID :one
SELECT uuid, name, plugin_config, view_position, created_at, updated_at
FROM node_plugins
WHERE uuid = $1
`

func (q *Queries) GetNodePluginByUUID(ctx context.Context, uuid pgtype.UUID) (NodePlugin, error) {
	row := q.db.QueryRow(ctx, getNodePluginByUUID, uuid)
	var i NodePlugin
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.PluginConfig,
		&i.ViewPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodePlugins = `-- name: ListNodePlugins :many
SELECT uuid, name, plugin_config, view_position, created_at, updated_at
FROM node_plugins
ORDER BY view_position ASC
`

func (q *Queries) ListNodePlugins(ctx context.Context) ([]NodePlugin, error) {
	rows, err := q.db.Query(ctx, listNodePlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodePlugin
	for rows.Next() {
		var i NodePlugin
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PluginConfig,
			&i.ViewPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
