name: Build And Push Subscription Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  send-start-deploy-telegram-message:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: info
          notify_fields: 'repository,branch,commit,workflow'
          title: 'Build started'

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [send-start-deploy-telegram-message]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/exodus-sub
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            SUB_APP_VERSION=${{ github.ref_name }}

  send-telegram-message:
    name: Send Telegram message
    needs: [build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: success
          notify_fields: 'repository,branch,commit,workflow'
          title: 'Build finished'

  notify-on-error:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    if: failure()
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Send Telegram message
        uses: proDreams/actions-telegram-notifier@main
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          status: error
          notify_fields: 'repository,branch,commit,workflow'
          title: 'Build failed'